# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ceb2fdbc34c906d13a38ca844c8451ee837ca9ef15ee97b4ba0ae7b4e5369361b64fcffc7c28437757fa2bcf3ec887443e4c32a58d27d26fdd4732ab7d137d8

test:
  secret_key_base: 623568166d0ef0c246969eed802ee71c9c7fe7971b8fc2e37e7414e035e65dd031d7e5cd21f08b36d9bde0388204f9542a6b69b29ea3fb0f0893f4f7fc264279

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
